freelancer:
    path:     /
    defaults: { _controller: "FreelancerMainBundle:Freelancer:index" }

freelancer_show:
    path:     /{id}/show
    defaults: { _controller: "FreelancerMainBundle:Freelancer:show" }

freelancer_new:
    path:     /new
    defaults: { _controller: "FreelancerMainBundle:Freelancer:new" }

freelancer_create:
    path:     /create
    defaults: { _controller: "FreelancerMainBundle:Freelancer:create" }
    methods:  POST

freelancer_edit:
    path:     /{id}/edit
    defaults: { _controller: "FreelancerMainBundle:Freelancer:edit" }

freelancer_update:
    path:     /{id}/update
    defaults: { _controller: "FreelancerMainBundle:Freelancer:update" }
    methods:  [POST, PUT]

freelancer_delete:
    path:     /{id}/delete
    defaults: { _controller: "FreelancerMainBundle:Freelancer:delete" }
    methods:  [POST, DELETE]
