imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
            node: C:\Program Files\nodejs
            node_paths: [C:\Program Files\nodejs\node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
# braincrafted Configuration
braincrafted_bootstrap:
    less_filter: less
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: false
        twig: false
        knp_menu: false
        knp_paginator: false
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
# FosUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Freelancer\MainBundle\Entity\User
    service:
        user_manager: pugx_user_manager
# pugx_multi_user Configuration
pugx_multi_user:
  users:
    admin:
        entity: 
          class: Freelancer\MainBundle\Entity\Admin
#          factory: 
        registration:
          form: 
            type: Freelancer\MainBundle\Form\Type\RegistrationAdminType
            name: admin_user_registration
            validation_groups:  [Registration, Default]
          template: FreelancerMainBundle:Registration:Admin.html.twig 
    freelancer:
        entity: 
          class: Freelancer\MainBundle\Entity\Freelancer
#          factory: 
        registration:
          form: 
            type: Freelancer\MainBundle\Form\Type\RegistrationFreelancerType
            name: freelancer_user_registration
            validation_groups:  [Registration, Default]
          template: FreelancerMainBundle:Registration:Freelancer.html.twig
        profile:
          form:
            type: Freelancer\MainBundle\Form\FreelancerType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    jobowner:
        entity: 
          class: Freelancer\MainBundle\Entity\Jobowner
        registration:
          form: 
            type: Freelancer\MainBundle\Form\Type\RegistrationJobownerType
            name: jobowner_user_registration
          template: FreelancerMainBundle:Registration:Jobowner.html.twig
        profile:
          form:
            type: Freelancer\MainBundle\Form\JobownerType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 


imports:
    - { resource: @FreelancerMainBundle/Resources/config/admin.yml }

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
nomaya_social:
    buttons:
        facebook:
            url:            null
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      false
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "L'Equipe cartedevisitevirtuelle.fr"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:            
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    links: 
        facebook:           "http://www.facebook.com/yann.chauvel"
        googleplus:         "https://plus.google.com/105931415830389032796"
    theme:                  'default' # optional